# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_fusion'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "alexanderallen/centos-6.5-x86_64-minimal"
  config.vm.provision "docker",
      images: ["centos"]
end
