# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.define 'docker_host_vm' do |node|          
    
    node.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = __FILE__.sub(%r{docker_container/Vagrantfile$},'host_vm/VagrantFile')
      d.build_dir = "."
      d.remains_running = true
      d.name = 'apache_container'
      d.ports = ['8080:80']
    end
    
  end  
  
end
